server:
  port: 80

# eureka配置
eureka:
  client:
    # 将自己注册进eureka
    register-with-eureka: false
    # 是否从eureka上获取所有注册信息，就是获取其他服务
    fetch-registry: true
    service-url:
      # 服务在这个地址去注册才能使用
#      defaultZone: http://localhost:7001/eureka
      # 集群版
      defaultZone: http://localhost:7001/eureka, http://localhost:7002/eureka
spring:
  application:
    name: cloud-openfeign-order-service

# 设置feign客户端超时时间，其内部是支持ribbon的
ribbon:
  # 建立连接所用时间
  ReadTimeout: 5000
  # 每个方法可等待时间
  ConnectTimeout: 5000

# 配置feign的日志
logging:
  level:
    # feign日志以什么级别来监控哪个接口
    cn.mb.springcloud.service.PaymentService: debug
