server:
  port: 8080

spring:
  application:
    name: reviewCode
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
