server:
  port: 9001

spring:
  application:
    name: nacos-provider
  # 设置注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

# 暴露监控服务
management:
  endpoints:
    web:
      exposure:
        include: "*"